### ISSUE TITLE
Assertion error with gsts version 5.0.3

### ISSUE THREAD

**Issue by brianrider** [ruimarinho/gsts#106]
The stack is below:

```
gsts --aws-profile {profile-name] --aws-region us-west-2 --aws-role-arn arn:aws:iam::{role-name} --playwright-engine-executable-path "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" --json --idp-id {idp-name} --no-credentials-cache --sp-id {sp-name} --clean --force
⚠ User is not authenticated, spawning headful instance
✖ Error: Assertion error
    at assert (/usr/local/Cellar/gsts/5.0.3/libexec/lib/node_modules/gsts/node_modules/playwright-core/lib/utils/utils.js:350:21)
    at CRSession._onMessage (/usr/local/Cellar/gsts/5.0.3/libexec/lib/node_modules/gsts/node_modules/playwright-core/lib/server/chromium/crConnection.js:222:25)
    at CRConnection._onMessage (/usr/local/Cellar/gsts/5.0.3/libexec/lib/node_modules/gsts/node_modules/playwright-core/lib/server/chromium/crConnection.js:113:26)
    at Immediate.<anonymous> (/usr/local/Cellar/gsts/5.0.3/libexec/lib/node_modules/gsts/node_modules/playwright-core/lib/server/pipeTransport.js:71:42)
    at process.processImmediate (node:internal/timers:478:21)
```

Please note I'm not getting this error with gsts 5.0.2

This is on a macbook pro with OS 13.4

**Comment by ruimarinho** [comment]
Hi @brianrider are you able to share a copy of your assertion XML when using the verbose setting and then masking all sensitive data?
