### ISSUE TITLE
v2.3.0-beta.1 hangs instead of logging in

### ISSUE THREAD

**Issue by thepatrick** [ruimarinho/gsts#15]
Need to dig in to this a bit more, but:

```
gsts \
    --aws-role-arn arn:aws:iam::ACC1:role/ROLE1,arn:aws:iam::ACC1:saml-provider/PROVIDER \
    --aws-session-duration 28800 \
    --sp-id "$OUR_SPID" \
    --idp-id "$OUR_IDPID" \
    --username "$MY_USER" \
    --aws-profile "$MY_AWS_PROFILE" \
    --enable-experimental-u2f-support \
    --verbose
```

Gives me:

```
ℹ Attempting to retrieve session expiration credentials
ℹ Parsed SAML assertion {
  attributes: [
    {
      name: 'https://aws.amazon.com/SAML/Attributes/RoleSessionName',
      value: [ 'MY_SESSION_NAME', [length]: 1 ]
    },
    {
      name: 'https://aws.amazon.com/SAML/Attributes/Role',
      value: [
        'arn:aws:iam::ACC1:role/ROLE1,arn:aws:iam::ACC1:saml-provider/PROVIDER',
        ...
        [length]: 3
      ]
    },
    {
      name: 'https://aws.amazon.com/SAML/Attributes/SessionDuration',
      value: [ '28800', [length]: 1 ]
    },
    [length]: 3
  ]
}
ℹ Parsed default IDP SessionDuration attribute with value 28800
ℹ Parsed Role attribute with value [
  Role {
    name: 'ROLE1',
    roleArn: 'arn:aws:iam::ACC1:role/ROLE1',
    principalArn: 'arn:aws:iam::ACC1:saml-provider/PROVIDER',
    sessionDuration: 28800
  },
  ...
  [length]: 3
]
ℹ Found custom role ARN "arn:aws:iam::ACC1:role/ROLE1" with principal ARN "arn:aws:iam::ACC1:saml-provider/PROVIDER"
ℹ An error has ocurred while authenticating Error: connect ETIMEDOUT 169.254.169.254:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {
  message: 'Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1',
  errno: 'ETIMEDOUT',
  code: 'CredentialsError',
  syscall: 'connect',
  address: '169.254.169.254',
  port: 80,
  time: 2020-04-24T01:40:03.373Z,
  originalError: {
    message: 'Could not load credentials from any providers',
    errno: 'ETIMEDOUT',
    code: 'CredentialsError',
    syscall: 'connect',
    address: '169.254.169.254',
    port: 80,
    time: 2020-04-24T01:40:03.373Z,
    originalError: {
      message: 'EC2 Metadata roleName request returned error',
      errno: 'ETIMEDOUT',
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '169.254.169.254',
      port: 80,
      time: 2020-04-24T01:40:03.373Z,
      originalError: [Object]
    }
  }
}
(node:72095) UnhandledPromiseRejectionWarning: TypeError: logger.fail is not a function
    at Page.<anonymous> (/Users/MY_USER/.nvm/versions/node/v12.16.1/lib/node_modules/gsts/index.js:262:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:72095) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:72095) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
ℹ Request to "https://signin.aws.amazon.com/saml" has been aborted
```

**Comment by ruimarinho** [comment]
The IAM fetch implicitly requires a valid set of credentials that may not be directly tied to the IAM role in question, so I've updated the logic to make it less prone to those conditions.

In terms of hanging, all unhandled rejections should now return control back to the terminal.

Thanks for the bug report. Should be fixed in https://github.com/ruimarinho/gsts/releases/tag/v2.3.0-beta.2.

**Comment by thepatrick** [comment]
Fantastic, thank you!
