### ISSUE TITLE
Error `Cannot find module ./credentials-manager`

### ISSUE THREAD

**Issue by nikhils5501** [ruimarinho/gsts#18]
I used `yarn` to install `gsts`.
However, I get this error:

```
[root@mbp]# gsts
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './credentials-manager'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/sbin/gsts:7:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

[root@mbp]#

**Comment by ruimarinho** [comment]
@nikhils5501 what's your OS?

**Comment by nikhils5501** [comment]
I'm trying to install it on an Amazon Linux EC2

**Comment by ruimarinho** [comment]
Can you browser to the directory where gsts was installed and paste the output of `ls -la` here?

**Comment by nikhils5501** [comment]
I was able to get it working with `yarn` install. `npm` threw permission errors even when running it as `sudo`
