### ISSUE TITLE
Plist file generated from --daemon command has invalid option

### ISSUE THREAD

**Issue by dtardoin** [ruimarinho/gsts#42]
The plist file generated from the `--daemon` flag has this option: 
```
      <string>--engine-executable-path=null</string>
```

This is even the case when ` --engine-executable-path` isn't used. 

Which is causing puppeteer to error because it can't find browser `null`: 
```
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/usr/local/lib/node_modules/gsts/node_modules/puppeteer/lib/Launcher.js:750:14)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/gsts/node_modules/puppeteer/lib/Launcher.js:741:65)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:485:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Error: Failed to launch the browser process! spawn null ENOENT
```

Fixable on my end by just removing that configuration option from the file.
Ran into this issue in 3.0.2, but it might have happened in earlier versions.

**Comment by ruimarinho** [comment]
Thanks for the report! Fixed in 3.0.3.
