### ISSUE TITLE
ROLE_NOT_FOUND_ERROR

### ISSUE THREAD

**Issue by lizthegrey** [ruimarinho/gsts#8]
```
Attempting to retrieve session expiration credentials
Session has expired on 2020-04-02T14:23:16.000Z
Parsed SAML assertion { attributes:
   [ { name: 'https://aws.amazon.com/SAML/Attributes/RoleSessionName',
       value: [Array] },
     { name: 'https://aws.amazon.com/SAML/Attributes/Role',
       value: [Array] },
     { name: 'https://aws.amazon.com/SAML/Attributes/SessionDuration',
       value: [Array] } ] }
Found SessionDuration attribute 43200
Found Role ARN arn:aws:iam::[snip]:role/platform
Found Principal ARN arn:aws:iam::[snip]:saml-provider/google
(node:29547) UnhandledPromiseRejectionWarning: ReferenceError: ROLE_NOT_FOUND_ERROR is not defined
    at Page.page.on (/home/lizf/.config/yarn/global/node_modules/gsts/index.js:417:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:29547) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29547) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This still happens when I run --clear and log in again. However, logging in via browser still succeeds at accessing AWS console.

**Comment by lizthegrey** [comment]
Oh, this is fixed in a later release :)
