### ISSUE TITLE
gsts v.5.0.0 missing files

### ISSUE THREAD

**Issue by gregbarski** [ruimarinho/gsts#85]
The is a problem running following command on version 5.0.0 on Windows 11

```PS C:\Windows\System32> gsts --sp-id 9********2 --idp-id *********** --username [*********@****.**]--aws-profile default --force --verbose --clean
file:///C:/Users/*****************/AppData/Roaming/npm/node_modules/gsts/credentials-manager.js:11
import { chmod, mkdir, readFile, writeFile, constants } from 'node:fs/promises';
                                            ^^^^^^^^^
SyntaxError: The requested module 'node:fs/promises' does not provide an export named 'constants'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:104:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:149:5)
    at async Loader.import (internal/modules/esm/loader.js:177:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)```
    
    Gsts version 5.0.0
    Node version v14.17.0 or latest 19.6.1
    
Not sure whether it is a local problem or not really.

**Comment by gregbarski** [comment]
I got version 19.6.1

**Comment by ruimarinho** [comment]
It might be installed but that's not the one in use though. Make sure `node -v` is reporting the right version.
